### ISSUE TITLE
issues with generated rust code

### ISSUE THREAD

**Issue by jordy25519** [InjectiveLabs/injective-proto#3]
apart from #2 , all the modules under `chain/injective/*` are unusable due to issues with the generated code.

it seems like the `mod.rs` are expecting all the generated structs to be in a single flat module, not nested as they really are.
can't fix externally as need access to the .proto files

**Comment by jordy25519** [comment]
ok I see the rust_zip has different files entirely so I guess proposal here is to remove `rust_old` since its broken and outdated

**Comment by allanbrondumkr** [comment]
Works here

**Comment by jordy25519** [comment]
this got resolved awhile ago, closing
